# -*- coding: utf-8 -*-
"""kadai_001.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PDqZr1Es2DnFannHY9_JZI7ZV9jBXxWl
"""

from openpyxl import Workbook
from datetime import datetime

# Get the current date in the format YYYYMMDD
current_date = datetime.now().strftime("%Y%m%d")

# Create a new workbook
workbook = Workbook()
ws = workbook.active

# Header
ws['B2'] = '請求書'
header_data = {
    'B4': '株式会社ABC',
    'F4': 'No.',
    'G4': '0001',
    'B5': '〒101-0022 東京都千代田区神田練塀町300',
    'F5': '日付',
    'G5': current_date,
    'B6': 'TEL:03-1234-5678 FAX:03-1234-5678',
    'B7': '担当者名:鈴木一郎 様'
}
for key, value in header_data.items():
    ws[key] = value

# Itemized list
item_list = [
    ('B10', '商品名'), ('C10', '数量'), ('D10', '単価'), ('E10', '金額'),
    ('B11', '商品Ａ'), ('C11', 2, 'D11', 10000, 'E11', 20000),
    ('B12', '商品Ｂ'), ('C12', 1, 'D12', 15000, 'E12', 15000),
    ('E13', 35000)
]
for data in item_list:
    for i in range(0, len(data), 2):
        ws[data[i]] = data[i + 1]

# Summary
summary_data = {
    'B15': '小計', 'E15': 35000,
    'B16': '消費税', 'E16': 3500,
    'B17': '合計', 'E17': 38500
}
for key, value in summary_data.items():
    ws[key] = value

# Save the workbook with the current date in the filename
file_name = f"請求書_{current_date}.xlsx"
workbook.save(file_name)