# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yMhxiI36HzAJymoxScn5h2rBElXVu59Y
"""

import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import PatternFill
from openpyxl.utils.dataframe import dataframe_to_rows


# 2022年度のデータを読み取り
df_2022 = pd.read_excel('2022_年間売上表.xlsx', sheet_name='Sheet1')

# 2023年度のデータを読み取り
df_2023 = pd.read_excel('2023_年間売上表.xlsx', sheet_name='Sheet1')

# データフレームを連結
df_concatenated = pd.concat([df_2022, df_2023])

# 商品と売上年ごとにグループ化し、合計金額に集約
df_grouped = df_concatenated.groupby(['商品', '売上年']).agg({'金額（千円）': 'sum'}).reset_index()

# 新しいExcelファイルを作成
excel_file = '売上集計表.xlsx'

# Excelファイルを作成
workbook = Workbook()
sheet = workbook.active

# データフレームの内容を書き込み
for row in dataframe_to_rows(df_grouped, index=False, header=True):
    sheet.append(row)

# ヘッダー部分の書式を変更（薄いグレー）
header_cells = sheet[1]
grey_fill = PatternFill(patternType='solid', fgColor='F2F2F2')
for cell in header_cells:
    cell.fill = grey_fill

# Excelファイルを保存
workbook.save(excel_file)